{
  "textPayload": "FirebaseAppError: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.\n    at AppStore.getApp (/workspace/node_modules/firebase-admin/lib/app/lifecycle.js:65:19)\n    at FirebaseNamespaceInternals.app (/workspace/node_modules/firebase-admin/lib/app/firebase-namespace.js:54:35)\n    at FirebaseNamespace.app (/workspace/node_modules/firebase-admin/lib/app/firebase-namespace.js:256:30)\n    at FirebaseNamespace.ensureApp (/workspace/node_modules/firebase-admin/lib/app/firebase-namespace.js:266:24)\n    at FirebaseNamespace.fn (/workspace/node_modules/firebase-admin/lib/app/firebase-namespace.js:136:25)\n    at Object.<anonymous> (/workspace/server.js:29:18)\n    at Module._compile (node:internal/modules/cjs/loader:1364:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)\n    at Module.load (node:internal/modules/cjs/loader:1203:32)\n    at Module._load (node:internal/modules/cjs/loader:1019:12) {",
  "insertId": "67bc8b23000357b075c75018",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "project_id": "tricykol-b2296",
      "service_name": "otp-service",
      "revision_name": "otp-service-00002-8hg",
      "configuration_name": "otp-service",
      "location": "asia-southeast1"
    }
  },
  "timestamp": "2025-02-24T15:07:15.219056Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00fd7d7337a7db9f22c64d862c9153050432ce0dcf6b7bb8b1a1f1d610feed2732656c0564033f36cd01f5665fbd9989cab46cd2b368ee03b06e7196fbd8b74ea838808b77939b"
  },
  "logName": "projects/tricykol-b2296/logs/run.googleapis.com%2Fstderr",
  "receiveTimestamp": "2025-02-24T15:07:15.502880430Z",
  "errorGroups": [
    {
      "id": "CIri4-3SoMvhoQE"
    }
  ]
}

{
  "textPayload": "Default STARTUP TCP probe failed 1 time consecutively for container \"otp-service-1\" on port 8080. The instance was not started.",
  "insertId": "67bc8b230009d1134a75f2a4",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "project_id": "tricykol-b2296",
      "location": "asia-southeast1",
      "service_name": "otp-service",
      "configuration_name": "otp-service",
      "revision_name": "otp-service-00002-8hg"
    }
  },
  "timestamp": "2025-02-24T15:07:15.643347Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00fd7d7337a7db9f22c64d862c9153050432ce0dcf6b7bb8b1a1f1d610feed2732656c0564033f36cd01f5665fbd9989cab46cd2b368ee03b06e7196fbd8b74ea838808b77939b"
  },
  "logName": "projects/tricykol-b2296/logs/run.googleapis.com%2Fvarlog%2Fsystem",
  "receiveTimestamp": "2025-02-24T15:07:15.897928096Z"
}

{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 9,
      "message": "Ready condition status changed to False for Revision otp-service-00002-8hg with message: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.\n\nLogs URL: https://console.cloud.google.com/logs/viewer?project=tricykol-b2296&resource=cloud_run_revision/service_name/otp-service/revision_name/otp-service-00002-8hg&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22otp-service%22%0Aresource.labels.revision_name%3D%22otp-service-00002-8hg%22 \nFor more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start"
    },
    "serviceName": "run.googleapis.com",
    "methodName": "/Services.ReplaceService",
    "resourceName": "namespaces/tricykol-b2296/revisions/otp-service-00002-8hg",
    "response": {
      "metadata": {
        "name": "otp-service-00002-8hg",
        "namespace": "666017533126",
        "selfLink": "/apis/serving.knative.dev/v1/namespaces/666017533126/revisions/otp-service-00002-8hg",
        "uid": "e943eb76-8958-4d7c-a6b4-feb80dc6bff3",
        "resourceVersion": "AAYu5LIYoYY",
        "generation": 1,
        "creationTimestamp": "2025-02-24T15:07:07.551088Z",
        "labels": {
          "client.knative.dev/nonce": "kwwkdojgjf",
          "serving.knative.dev/configuration": "otp-service",
          "serving.knative.dev/configurationGeneration": "2",
          "serving.knative.dev/service": "otp-service",
          "serving.knative.dev/serviceUid": "c4767af4-77a9-4211-a91a-ae18730e18f2",
          "serving.knative.dev/route": "otp-service",
          "run.googleapis.com/satisfiesPzs": "true",
          "cloud.googleapis.com/location": "asia-southeast1",
          "run.googleapis.com/startupProbeType": "Default"
        },
        "annotations": {
          "run.googleapis.com/client-name": "gcloud",
          "run.googleapis.com/client-version": "506.0.0",
          "run.googleapis.com/startup-cpu-boost": "true",
          "run.googleapis.com/operation-id": "2a66697d-8b2b-4e02-b4ae-a9eaf92cc3ca",
          "autoscaling.knative.dev/maxScale": "100",
          "serving.knative.dev/creator": "tricykol707@gmail.com"
        },
        "ownerReferences": [
          {
            "kind": "Configuration",
            "name": "otp-service",
            "uid": "4abee2ba-aa40-4405-892b-636d99d9c520",
            "apiVersion": "serving.knative.dev/v1",
            "controller": true,
            "blockOwnerDeletion": true
          }
        ]
      },
      "apiVersion": "serving.knative.dev/v1",
      "kind": "Revision",
      "spec": {
        "containerConcurrency": 80,
        "timeoutSeconds": 300,
        "serviceAccountName": "666017533126-compute@developer.gserviceaccount.com",
        "containers": [
          {
            "name": "otp-service-1",
            "image": "asia-southeast1-docker.pkg.dev/tricykol-b2296/cloud-run-source-deploy/otp-service@sha256:99632c1d583aaa6efdbacbeb69af879ea5522b95113f7215d5893de3efcfcb50",
            "ports": [
              {
                "name": "http1",
                "containerPort": 8080
              }
            ],
            "env": [
              {
                "name": "SEMAPHORE_API_KEY",
                "valueFrom": {
                  "secretKeyRef": {
                    "key": "latest",
                    "name": "semaphore-api-key"
                  }
                }
              }
            ],
            "resources": {
              "limits": {
                "cpu": "1000m",
                "memory": "512Mi"
              }
            },
            "startupProbe": {
              "timeoutSeconds": 240,
              "periodSeconds": 240,
              "failureThreshold": 1,
              "tcpSocket": {
                "port": 8080
              }
            }
          }
        ]
      },
      "status": {
        "observedGeneration": 1,
        "conditions": [
          {
            "type": "Ready",
            "status": "False",
            "reason": "HealthCheckContainerError",
            "message": "The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.\n\nLogs URL: https://console.cloud.google.com/logs/viewer?project=tricykol-b2296&resource=cloud_run_revision/service_name/otp-service/revision_name/otp-service-00002-8hg&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22otp-service%22%0Aresource.labels.revision_name%3D%22otp-service-00002-8hg%22 \nFor more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start",
            "lastTransitionTime": "2025-02-24T15:07:15.643782Z"
          },
          {
            "type": "ContainerHealthy",
            "status": "False",
            "reason": "HealthCheckContainerError",
            "message": "The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.\n\nLogs URL: https://console.cloud.google.com/logs/viewer?project=tricykol-b2296&resource=cloud_run_revision/service_name/otp-service/revision_name/otp-service-00002-8hg&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22otp-service%22%0Aresource.labels.revision_name%3D%22otp-service-00002-8hg%22 \nFor more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start",
            "lastTransitionTime": "2025-02-24T15:07:15.643782Z"
          },
          {
            "type": "ContainerReady",
            "status": "True",
            "message": "Container image import completed in 2.41s.",
            "lastTransitionTime": "2025-02-24T15:07:10.542600Z"
          },
          {
            "type": "ResourcesAvailable",
            "status": "True",
            "message": "Provisioning imported containers completed in 1.59s. Checking container health.",
            "lastTransitionTime": "2025-02-24T15:07:12.133731Z"
          },
          {
            "type": "Retry",
            "status": "True",
            "reason": "ImmediateRetry",
            "message": "System will retry after 0:00:00 from lastTransitionTime for attempt 0.",
            "lastTransitionTime": "2025-02-24T15:07:12.133731Z",
            "severity": "Info"
          }
        ],
        "logUrl": "https://console.cloud.google.com/logs/viewer?project=tricykol-b2296&resource=cloud_run_revision/service_name/otp-service/revision_name/otp-service-00002-8hg&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22otp-service%22%0Aresource.labels.revision_name%3D%22otp-service-00002-8hg%22",
        "imageDigest": "asia-southeast1-docker.pkg.dev/tricykol-b2296/cloud-run-source-deploy/otp-service@sha256:99632c1d583aaa6efdbacbeb69af879ea5522b95113f7215d5893de3efcfcb50",
        "containerStatuses": [
          {
            "name": "otp-service-1",
            "imageDigest": "asia-southeast1-docker.pkg.dev/tricykol-b2296/cloud-run-source-deploy/otp-service@sha256:99632c1d583aaa6efdbacbeb69af879ea5522b95113f7215d5893de3efcfcb50"
          }
        ]
      },
      "@type": "type.googleapis.com/google.cloud.run.v1.Revision"
    }
  },
  "insertId": "dmk56ddmj5s",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "location": "asia-southeast1",
      "service_name": "otp-service",
      "configuration_name": "otp-service",
      "revision_name": "otp-service-00002-8hg",
      "project_id": "tricykol-b2296"
    }
  },
  "timestamp": "2025-02-24T15:07:15.666482Z",
  "severity": "ERROR",
  "logName": "projects/tricykol-b2296/logs/cloudaudit.googleapis.com%2Fsystem_event",
  "receiveTimestamp": "2025-02-24T15:07:16.585811416Z"
}


